config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'items#index'
  resources :items do
    collection do
      get :find
    end
    resources :item_reviews,  only: [:new, :index, :create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
    post '/add_item' => 'carts#add_item'
    post '/update_item' => 'carts#update_item'
    delete '/delete_item' => 'carts#delete_item'
    post :pay, on: :member
  end
  get 'items/find', to: 'items#find_column', as: 'find_column'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  resources :categories,  only: [:new, :create, :show] do
    resource :item_categories, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  resources :carts, only: [:show] do
    get '/bill_confirm' => 'carts#bill_confirm'
    post :pay, on: :member
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
  validates :stocks, presence: true, numericality: { only_integer: true, greater_than: -1 }
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :item_categories
  has_many :items, through: :item_categories
  validates :name, presence: true, length: { minimum: 1 }, uniqueness: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :item_reviews
  has_many :item_categories
  has_many :categories, through: :item_categories
  accepts_nested_attributes_for :item_categories
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :cart_items
  has_many :cart, through: :cart_items
  has_one_attached :image
  validates :name, presence: true, length: { in: 1..50 }, uniqueness: true
  validates :stocks, presence: true, numericality: { only_integer: true, greater_than: -1 }
  validates :description, presence: true, length: { minimum: 3 }
  validates :hide, inclusion: { in: [true, false] }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :user_id?

  def user_id?
    i = user_id
    admin = User.find(user_id).admin
    if admin != true
      errors.add(:name, ' はadmin権限を持ったユーザーのみ登録できます。')
    end
  end
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item_review.rb
class ItemReview < ActiveRecord::Base
  belongs_to :item
  validates :review, presence: true, length: { minimum: 1 }, uniqueness: true
end

app/models/itemreview.rb
class ItemReview < ActiveRecord::Base
  belongs_to :item
  validates :review, presence: true, length: { minimum: 1 }, uniqueness: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :item
  belongs_to :user
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true, length: { in: 1..40 }, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item
  
  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, only: [:add_item, :update_item, :delete_item]
  before_action :set_search

  def show
    @cart_items = current_cart.cart_items
  end

  def add_item
    if @cart_item.blank?
      @cart_item = current_cart.cart_items.build(item_id: params[:item_id])
    end
    @cart_item.stocks += params[:stocks].to_i
    @cart_item.save
    redirect_to current_cart
  end

  def update_item
    @cart_item.update(stocks: params[:stocks].to_i)
    redirect_to current_cart
  end

  def delete_item
    @cart_item.destroy
    redirect_to cart_path(session[:cart_id])
  end

  def bill_confirm
    @cart_items = current_cart.cart_items
    all_price = 0
    @cart_items.each do |c|
      @total_price = c.stocks * c.item.price
      @all_price = @all_price.to_i + @total_price.to_i
    end
  end

  def pay
    Payjp.api_key = "sk_test_fb0dd938a4a447658641aa92"
    charge = Payjp::Charge.create(
      :amount => params[:amount],
      :card => params['payjp-token'],
      :currency => 'jpy',
    )
    if charge
      @cart_items = current_cart.cart_items
      @cart_items.each do |item|
        result_stock = item.item.stocks.to_i - item.stocks.to_i
        item.item.update_attribute(:stocks, result_stock)
        item.destroy
      end
      
    end
    redirect_to root_path, notice: 'ご購入、ありがとうございました。'
  end


  private

  def cart_params
    params.require(:cart).permit(cart_items: [:id, :item_id, :cart_id])
  end

  def setup_cart_item!
    @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_search
  # TODO
  # before_destroy :should_not_destroy_if_stock, prepend: true

  def new
    @item = Item.new
    @item.item_categories.build
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "商品の登録をしました。"
      redirect_back(fallback_location: items_path)
    else
      flash[:error] = "商品の登録に失敗しました。"
      render :new
    end
  end

  def index
    @items = Item.all
    @category = Category.all
  end

  def show
    @item = Item.find(params[:id])
    @like = Like.new
  end

  def edit
    @item = Item.find(params[:id])
    @item.item_categories.build
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      flash[:error] = "商品の更新に失敗しました。"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "商品は削除されました。"
    redirect_back(fallback_location: items_path)
  end

  def pay
    @item = Item.find(params[:id])
    Payjp.api_key = "sk_test_fb0dd938a4a447658641aa92"
    charge = Payjp::Charge.create(
      :amount => @item.price,
      :card => params['payjp-token'],
      :currency => 'jpy',
    )
    if charge
      i = @item.stocks-1
      @item.update_attribute(:stocks, i)
      @item.save
    end
    redirect_to @item, notice: 'ご購入、ありがとうございました。'
  end

  def find
    @find_items = @q.result
  end

  private

  def item_params
    params.require(:item).permit(:name, :stocks, :price, :description, :hide, :user_id, :image, item_categories_attributes: [:id, :category_id])
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください。"
    redirect_back(fallback_location: sign_in_path)
    end
  end

  def admin_user
    redirect_back(fallback_location: root_url) unless current_user.admin?
  end

  # TODO
  # def should_not_destroy_if_stock
  #   throw(:abort) if stock?
  # end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(item_id: params[:item_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user
  def new
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_categories_helper.rb
module ItemCategoriesHelper
end

app/helpers/item_reviews_helper.rb
module ItemReviewsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/bill_confirm.html.erb
<h1>Carts#bill_confirm</h1>
<p>Find me in app/views/carts/bill_confirm.html.erb</p>
<p>購入商品の確認</p>
<% @cart_items.each do |item| %>
<% price = item.item.price * item.stocks %>
  <p>
    商品名：<%= link_to item.item.name, item_path(item.item.id) %>
  </p>
  <p>
    数量：<%= item.stocks %>
  </p>
  <p>価格：<%= item.item.price %>円</p>
  <p>この商品の合計金額：<%= price %>円
  <hr>
<% end %>
<p>総合計金額：<%= @all_price %>円</p>
<hr>
<p>こちらでよろしければカードで支払うボタンを押して、購入を完了してください。</p>
<%= form_with url: pay_cart_path(id: params[:cart_id]) do |form| %>
  <%= form.hidden_field :amount, value: @all_price %>
    <script type="text/javascript"
    src="https://checkout.pay.jp"
    class="payjp-button"
    data-key="pk_test_195e7aef15d83551e679aec3">
  </script>
<% end %>
<%= link_to 'カートへ戻る', current_cart %>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>
<p>カートに入っている商品</p>
<% @cart_items.each do |item| %>
<% price = item.item.price * item.stocks %>
  <p>
    商品名：<%= link_to item.item.name, item_path(item.item.id), data: {"turbolinks" => false} %>
  </p>
  <p>
    数量：<%= item.stocks %>
  </p>
  <p>価格：<%= item.item.price %>円</p>
  <p>商品の合計金額：<%= price %>円
  <%= form_with url: item_update_item_path(item.item.id) do |form| %>
    <%= form.number_field :stocks, min:1, max:item.item.stocks %>
    <%= form.hidden_field :item_id, value: item.id %>
    <%= form.submit "数量を変更する" %>
  <% end %>
  <%= button_to 'カートから削除する', item_delete_item_path(item.item.id), method: :delete %>
  <hr>
<% end %>
<%= link_to "商品購入ページ", cart_bill_confirm_path(current_cart.id), data: {"turbolinks" => false} %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>

<%= form_for @item do |f| %>
  
  <%= f.label :"商品名" %>
  <%= f.text_field :name %>
  
  <%= f.label :"在庫数" %>
  <%= f.number_field :stocks %>

  <%= f.label :"価格" %>
  <%= f.number_field :price %>

  <%= f.label :"商品概要" %>
  <%= f.text_field :description %>

  <%= f.label :"表示・非表示設定" %>
  <%= f.check_box :hide %>

  <%= f.label :"商品画像" %>
  <%= f.file_field :image %>

  <%= f.fields_for :item_categories do |c| %>
    <%= c.collection_select :category_id, Category.all, :id, :name, :prompt =>"カテゴリを選択してください。" %>
  <% end %>

  <%= f.submit "登録" %>
<% end %>

app/views/items/find.html.erb
<h1>Items#find</h1>

<% @find_items.each do |item| %>
  <div>
    <p>
    商品名：<%= link_to item.name, item_path(item.id), data: {"turbolinks" => false} %>
    </p>
    <p>
      在庫数：<%= item.stocks %>
    </p>
    <p>
      価格：<%= item.price %>
    </p>
    <p>
      商品説明：<%= item.description %>
    </p>
    <% unless item.categories.empty? %>
      <% item.categories.each do |cate| %>
        <p>
          カテゴリ：<%= cate.name %>
        </p>
      <% end %>
    <% end %>
    <p>ユーザーからいいねされた数：(<%= item.liked_users.count %>)</p>
    <% if user_signed_in? %>
      <% if current_user.admin == true %>
      <%= link_to "情報変更", edit_item_path(item.id) %>
      <%= link_to "削除", item_path(item.id), method: :delete, data: { confirm: "本当に削除してよろしいですか?" } %>
      <% end %>
    <% end %>
  </div>
  <hr>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin == true %>
  <%= link_to "商品登録", new_item_path %>
  <%= link_to "カテゴリ登録", new_category_path %>
  <% end %>
<% end %>

app/views/items/index.html.erb
<h1>Items#index</h1>
<%= search_form_for @q, url: find_items_path do |f| %>
  <%= f.label :商品名 %>
  <%= f.search_field :name_cont %>
  <%= f.label :価格 %>
  <%= f.number_field :price_gteq %>円以上〜
  <%= f.number_field :price_lt %>円未満
  <%= f.submit "検索" %>
<% end %>
<%= sort_link(@q, :name, "名前ソート") %>
<%= sort_link(@q, :price, "価格ソート") %>
<hr>
カテゴリ
<% @category.each do |f| %>
<table>
<tr>
<td>
  <%= link_to f.name, category_path(f.id)%>
  </td>
  </tr>
  </table>
<% end %>
<hr>
<% @items.each do |item| %>
  <div>
    <p>
    商品名：<%= link_to item.name, item_path(item.id), data: {"turbolinks" => false} %>
    </p>
    <p>
      在庫数：<%= item.stocks %>
    </p>
    <p>
      価格：<%= item.price %>
    </p>
    <p>
      商品説明：<%= item.description %>
    </p>
    <p>
    <% if item.image.attached? %>
      <%= image_tag item.image %>
    <% end %>
    </p>
    <% unless item.categories.empty? %>
      <% item.categories.each do |cate| %>
        <p>
          カテゴリ：<%= cate.name %>
        </p>
      <% end %>
    <% end %>
    <p>ユーザーからいいねされた数：(<%= item.liked_users.count %>)</p>
    <% if user_signed_in? %>
      <% if current_user.admin == true %>
      <%= link_to "情報変更", edit_item_path(item.id) %>
      <%= link_to "削除", item_path(item.id), method: :delete, data: { confirm: "本当に削除してよろしいですか?" } %>
      <% end %>
    <% end %>
  </div>
  <hr>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin == true %>
  <%= link_to "商品登録", new_item_path %>
  <%= link_to "カテゴリ登録", new_category_path %>
  <% end %>
<% end %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

<%= form_for @item do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <%= f.label :"商品名" %>
  <%= f.text_field :name %>
  
  <%= f.label :"在庫数" %>
  <%= f.number_field :stocks %>

  <%= f.label :"価格" %>
  <%= f.number_field :price %>

  <%= f.label :"商品概要" %>
  <%= f.text_field :description %>

  <%= f.label :"表示・非表示設定" %>
  <%= f.check_box :hide %>

  <%= f.label :"商品画像" %>
  <%= f.file_field :image %>

  <%= f.fields_for :item_categories do |c| %>
    <%= c.collection_select :category_id, Category.all, :id, :name, :prompt =>"カテゴリを選択してください。" %>
  <% end %>

  <%= f.submit "登録" %>

<% end %>

app/views/items/search.html.erb
<h1>Items#index</h1>

<% @items.each do |item| %>
  <div>
    <p>
    商品名：<%= link_to item.name, item_path(item.id), data: {"turbolinks" => false} %>
    </p>
    <p>
      在庫数：<%= item.stocks %>
    </p>
    <p>
      価格：<%= item.price %>
    </p>
    <p>
      商品説明：<%= item.description %>
    </p>
    <% unless item.categories.empty? %>
      <% item.categories.each do |cate| %>
        <p>
          カテゴリ：<%= cate.name %>
        </p>
      <% end %>
    <% end %>
    <p>ユーザーからいいねされた数：(<%= item.liked_users.count %>)</p>
    <% if user_signed_in?&& current_user.admin = 1 %>
    <%= link_to "情報変更", edit_item_path(item.id) %>
    <%= link_to "削除", item_path(item.id), method: :delete, data: { confirm: "本当に削除してよろしいですか?" } %>
    <% end %>
  </div>
  <hr>
<% end %>
<% if user_signed_in?&& current_user.admin = 1 %>
<%= link_to "商品登録", new_item_path %>
<%= link_to "カテゴリ登録", new_category_path %>

<% end %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>
    <p>
    商品名：<%= @item.name %>
    </p>
    <p>
      在庫数：<%= @item.stocks %>
    </p>
    <p>
      価格：<%= @item.price %>
    </p>
    <p>
      商品説明：<%= @item.description %>
    </p>
    <% unless @item.categories.empty? %>
      <% @item.categories.each do |cate| %>
        <p>
          カテゴリ：<%= cate.name %>
        </p>
      <% end %>
    <% end %>
    <% if @item.image.attached? %>
      <%= image_tag @item.image %>
    <% end %>
<% unless @item.item_reviews.empty? %>
  <% @item.item_reviews.each do |re| %>
    <p>口コミ：<%= re.review %></p>
  <% end %>
<% end %>
口コミ一覧
<%= link_to "口コミ一覧ページ", item_item_reviews_path(@item.id) %>
<h3>いいね件数: <%= @item.likes.count %></h3>
<% if user_signed_in? %>
  <%= link_to "口コミを書く", new_item_item_review_path(@item.id) %>
  <% if current_user.already_liked?(@item) %>
    <%= button_to 'いいねを取り消す', item_like_path(@item), method: :delete %>
  <% else %>
    <%= button_to 'いいね', item_likes_path(@item) %>
  <% end %>
<% end %>
<% unless @item.stocks < 1 %>
  <%= form_tag(action: :pay, method: :post) do %>
    <script type="text/javascript"
      src="https://checkout.pay.jp"
      class="payjp-button"
      data-key="pk_test_195e7aef15d83551e679aec3">
    </script>
  <% end %>
  <%= form_with url: item_add_item_path(@item) do |form| %>
    <%= form.number_field :stocks, min:1, max:@item.stocks %>
    <%= form.hidden_field :item_id, value: @item.id %>
    <%= form.submit 'カートに入れる' %>
  <% end %>
<% end %>